import { Inter } from "next/font/google";
import Head from "next/head";
import Stairs from "../components/Layout/Stairs"

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>nkyu portfolio</title>
        <meta name="description" content="Generated by createnext app" />
        <meta name="viewport" content="width=device-width,initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Stairs>
        <h1>Home Page</h1>
        <div>
          <p>lorem ipsum</p>
        </div>
      </Stairs>
    </>
  );
}
