import { Inter } from "next/font/google";
import Head from "next/head";
import Stairs from "../components/Layout/Stairs"
import Hero from '../components/Hero/'
import AboutMe from '../components/AboutMeSection'
import Projects from '../components/ProjectsSection'
import Clients from '../components/ClientsSection'

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>nkyu portfolio</title>
        <meta name="description" content="Generated by createnext app" />
        <meta name="viewport" content="width=device-width,initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <Stairs>
        <Clients />
        <AboutMe />
        <Projects />
      </Stairs>
    </>
  );
}
